# Generated by Django 2.2.12 on 2020-10-28 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0011_auto_20201023_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daterental',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='Airbnb.Property'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='2020-10-28 00:43:04.112716+00:00', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 0, 43, 4, 112685, tzinfo=utc)),
        ),
    ]
