# Generated by Django 2.2.12 on 2020-10-30 01:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Airbnb', '0013_auto_20201030_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default='2020-10-30 01:18:36.861220+00:00', max_length=70),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 30, 1, 18, 36, 861190, tzinfo=utc)),
        ),
    ]
